{% set name = "gds-dmt" %}
{% set version = "3.0.0" %}

# dependencies
{% set gds_base_version = "3.0.0" %}
{% set gds_lsmp_version = "3.0.0" %}
{% set gds_frameio_version = "3.0.0" %}
{% set ldas_tools_framecpp_version = "2.5.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://software.igwn.org/sources/source/{{ name }}-{{ version }}.tar.gz
  sha256: 6fd4b58a3c730592212bbb5f9d776c459bb6ee59262d9f672965e0d8ffc648e9

build:
  error_overlinking: true
  error_overdepending: true
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
    - pkg-config
  host:
    - gds-base >={{ gds_base_version }}
    - gds-base-gdstrig >={{ gds_base_version }}
    - gds-base-monitors >={{ gds_base_version }}
    - gds-frameio-base >={{ gds_frameio_version }}
    - gds-lsmp >={{ gds_lsmp_version }}
    - gds-services >={{ gds_base_version }}
    - jsoncpp
    - ldas-tools-al
    - ldas-tools-framecpp >={{ ldas_tools_framecpp_version }}
    - libboost-headers
    - root_base

outputs:
  - name: gds-dmt-base
    build:
      error_overlinking: true
      error_overdepending: true
      run_exports:
        - {{ pin_subpackage("gds-dmt-base", max_pin="x") }}
    requirements:
      build:
        - {{ compiler('cxx') }}
    files:
      - include/gds/calc_engine/
      - lib/libcalcengn.*
      - lib/pkgconfig/gdsdmtcalcengine.pc
    test:
      requires:
        - pkg-config
      commands:
        # check for library
        - test -f ${PREFIX}/lib/libcalcengn${SHLIB_EXT}  # [unix]
        # check for headers
        - test -d ${PREFIX}/include/gds/calc_engine/  # [unix]
        # check pkg-config
        - pkg-config --print-errors --exact-version "{{ version }}" gdsdmtcalcengine
    about:
      home: https://computing.docs.ligo.org/daswgweb/projects/dmt.html
      license: GPL-2.0-only
      license_family: GPL
      license_file: COPYING
      summary: GDS DMT package Core libraries

  - name: gds-dmt-monitors
    build:
      error_overlinking: true
      error_overdepending: true
      ignore_run_exports:
        # unused link removed on macOS
        - gds-lsmp  # [osx]
        - gds-services
      run_exports:
        - {{ pin_subpackage("gds-dmt-monitors", max_pin="x") }}
    requirements:
      build:
        - {{ compiler('cxx') }}
      host:
        - gds-base >={{ gds_base_version }}
        - gds-base-gdstrig >={{ gds_base_version }}
        - {{ pin_subpackage('gds-dmt-base', exact=True) }}
        - gds-frameio-base >={{ gds_frameio_version }}
        - gds-lsmp
        - gds-services >={{ gds_base_version }}
        - jsoncpp
        - ldas-tools-al
        - ldas-tools-framecpp
        - root_base
      run:
        - gds-services >={{ gds_base_version }}
    files:
      - bin/DMTGen
      - include/gds/generator/
      - include/gds/osc/
      - include/gds/CalibChan.hh
      - include/gds/DMTBase.hh
      - include/gds/DMTServer.hh
      - include/gds/DatEnv.hh
      - include/gds/DynConfig.hh
      - include/gds/FDCalibrate.hh
      - include/gds/FDEasyCalibrate.hh
      - include/gds/FilterDB.hh
      - include/gds/FilterModule.hh
      - include/gds/GDSPlot.hh
      - include/gds/GridWare.hh
      - include/gds/IfoResponse.hh
      - include/gds/LscCalib.hh
      - include/gds/LscEmul.hh
      - include/gds/LscPdBackout.hh
      - include/gds/MultiStream.hh
      - include/gds/OperStateCondList.hh
      - include/gds/PSD.hh
      - include/gds/TrigEnv.hh
      - include/gds/marker.hh
      - include/gds/plot_pars.hh
      - lib/libdmtenv.*
      - lib/libezcalib.*
      - lib/libgds_plotpkg.*
      - lib/libgenerator.*
      - lib/liblscemul.*
      - lib/libosc.*
      - lib/pkgconfig/gdsdmtenv.pc
      - lib/pkgconfig/gdsdmtezcalib.pc
      - lib/pkgconfig/gdsdmtosc.pc
      - lib/pkgconfig/gdsdmtplotpkg.pc
    test:
      requires:
        - pkg-config
      commands:
        # check for library
        - test -f ${PREFIX}/lib/libdmtenv${SHLIB_EXT}  # [unix]
        # check for headers
        - test -d ${PREFIX}/include/gds/generator/  # [unix]
        # check pkg-config
        - pkg-config --print-errors --exact-version "{{ version }}" gdsdmtenv
        - pkg-config --print-errors --exact-version "{{ version }}" gdsdmtezcalib
        - pkg-config --print-errors --exact-version "{{ version }}" gdsdmtosc
        - pkg-config --print-errors --exact-version "{{ version }}" gdsdmtplotpkg
    about:
      home: https://computing.docs.ligo.org/daswgweb/projects/dmt.html
      license: GPL-2.0-only
      license_family: GPL
      license_file: COPYING
      summary: Libraries used by DMT Monitor programs

  - name: gds-dmt-root
    build:
      error_overlinking: true
      error_overdepending: true
    requirements:
      build:
        - {{ compiler('cxx') }}
    files:
      - share/gds/macros/
      - share/gds/.rootrc
      - share/gds/root-version
    test:
      commands:
        - test -f ${PREFIX}/share/gds/macros/rootlogon.C  # [unix]
    about:
      home: https://computing.docs.ligo.org/daswgweb/projects/dmt.html
      license: GPL-2.0-only
      license_family: GPL
      license_file: COPYING
      summary: Root wrapper for gds classes

about:
  home: https://computing.docs.ligo.org/daswgweb/projects/dmt.html
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: LIGO Global Diagnostics System

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
